# Generated by Django 4.1.7 on 2023-07-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_ticket',
            name='price',
        ),
    ]
